import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { PromptEditor } from '../components/PromptEditor';
import { ActivityEditor } from '../components/ActivityEditor';
import { LiveClassroomDashboard } from '../components/LiveClassroomDashboard';
import { activitiesApi } from '../api/activities';
import type { ActivityDefinition } from '../types/activityDsl';

interface ActiveSessionItem {
  id: string;
  shareCode: string;
  status: string;
  createdAt: string;
  activityTitle: string;
}

export const TeacherDashboard: React.FC = () => {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<'ai_authoring' | 'live_classroom'>('ai_authoring');
  const [generatedDefinition, setGeneratedDefinition] = useState<ActivityDefinition | null>(null);
  const [activeShareCode, setActiveShareCode] = useState<string>('ABC-742');
  const [activeSessions, setActiveSessions] = useState<ActiveSessionItem[]>([]);

  const fetchActiveSessions = async () => {
    try {
      const activeToken = localStorage.getItem('access_token') || localStorage.getItem('token') || '';
      const sessions = await activitiesApi.getTeacherActiveSessions(activeToken);
      setActiveSessions(sessions || []);
      if (sessions && sessions.length > 0) {
        if (!activeShareCode || activeShareCode === 'ABC-742') {
          setActiveShareCode(sessions[0].shareCode);
        }
      }
    } catch (err) {
      console.error('Failed to fetch active sessions:', err);
    }
  };

  useEffect(() => {
    fetchActiveSessions();
  }, [activeTab]);

  const handleGenerated = (def: ActivityDefinition) => {
    setGeneratedDefinition(def);
  };

  const handlePublished = (shareCode: string) => {
    setActiveShareCode(shareCode);
    setActiveTab('live_classroom');
    fetchActiveSessions();
  };

  return (
    <div style={styles.container}>
      {/* Top Teacher Header & Navigation Tabs */}
      <header style={styles.header}>
        <div>
          <div style={styles.badge}>👩‍🏫 TEACHER AUTHORING & CLASSROOM DASHBOARD</div>
          <h1 style={styles.title}>Interactive Learning Platform</h1>
          <p style={styles.subtitle}>
            Welcome, {user?.firstName} {user?.lastName} ({user?.email})
          </p>
        </div>

        {/* Tab Navigation */}
        <div style={styles.tabBar}>
          <button
            onClick={() => setActiveTab('ai_authoring')}
            style={{
              ...styles.tabBtn,
              ...(activeTab === 'ai_authoring' ? styles.activeTabBtn : {}),
            }}
          >
            ✨ Create with AI
          </button>
          <button
            onClick={() => setActiveTab('live_classroom')}
            style={{
              ...styles.tabBtn,
              ...(activeTab === 'live_classroom' ? styles.activeTabBtn : {}),
            }}
          >
            🏫 Live Classroom Dashboard ({activeShareCode})
          </button>
        </div>
      </header>

      {/* Main Content Body based on Active Tab */}
      {activeTab === 'ai_authoring' && (
        <div style={styles.tabContent}>
          {!generatedDefinition ? (
            <PromptEditor onGenerated={handleGenerated} />
          ) : (
            <div style={styles.editorWrapper}>
              <div style={styles.bannerRow}>
                <span>✨ Draft Activity Generated by AI. Edit blocks below before publishing:</span>
                <button onClick={() => setGeneratedDefinition(null)} style={styles.resetPromptBtn}>
                  🔄 Start New Prompt
                </button>
              </div>
              <ActivityEditor
                initialDefinition={generatedDefinition}
                onPublished={handlePublished}
              />
            </div>
          )}
        </div>
      )}

      {activeTab === 'live_classroom' && (
        <div style={styles.tabContent}>
          <div style={styles.codeSelectorBar}>
            <label style={styles.codeLabel}>Active Session Share Join Code:</label>
            {activeSessions.length > 0 && (
              <select
                value={activeShareCode}
                onChange={(e) => setActiveShareCode(e.target.value)}
                style={styles.codeSelectDropdown}
              >
                {activeSessions.map((s) => (
                  <option key={s.id} value={s.shareCode}>
                    📖 {s.activityTitle} ({s.shareCode})
                  </option>
                ))}
              </select>
            )}
            <input
              type="text"
              value={activeShareCode}
              onChange={(e) => setActiveShareCode(e.target.value.toUpperCase())}
              style={styles.codeInput}
              placeholder="e.g. ABC-742"
            />
            <button onClick={fetchActiveSessions} style={styles.refreshSessionsBtn}>
              🔄 Refresh Sessions
            </button>
          </div>
          <LiveClassroomDashboard shareCode={activeShareCode} />
        </div>
      )}
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  container: { maxWidth: '1100px', margin: '1.5rem auto', padding: '0 1rem', display: 'flex', flexDirection: 'column', gap: '1.5rem' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', backgroundColor: '#ffffff', padding: '1.5rem', borderRadius: '12px', border: '1px solid #e5e7eb', boxShadow: '0 4px 10px rgba(0,0,0,0.02)' },
  badge: { display: 'inline-block', backgroundColor: '#dbeafe', color: '#1e40af', fontWeight: '800', fontSize: '0.75rem', padding: '0.25rem 0.75rem', borderRadius: '12px' },
  title: { fontSize: '1.75rem', fontWeight: '800', color: '#111827', margin: '0.4rem 0 0.2rem 0' },
  subtitle: { color: '#6b7280', fontSize: '0.9rem', margin: 0 },
  tabBar: { display: 'flex', gap: '0.5rem', backgroundColor: '#f3f4f6', padding: '0.35rem', borderRadius: '10px' },
  tabBtn: { padding: '0.6rem 1.1rem', borderRadius: '8px', border: 'none', backgroundColor: 'transparent', color: '#4b5563', fontWeight: '700', fontSize: '0.9rem', cursor: 'pointer' },
  activeTabBtn: { backgroundColor: '#ffffff', color: '#2563eb', boxShadow: '0 2px 4px rgba(0,0,0,0.05)' },
  tabContent: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  editorWrapper: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  bannerRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#f3e8ff', color: '#6b21a8', padding: '0.85rem 1.25rem', borderRadius: '10px', border: '1px solid #d8b4fe', fontWeight: '700', fontSize: '0.92rem' },
  resetPromptBtn: { backgroundColor: '#ffffff', color: '#6b21a8', border: '1px solid #c084fc', padding: '0.4rem 0.85rem', borderRadius: '6px', fontWeight: '700', cursor: 'pointer', fontSize: '0.82rem' },
  codeSelectorBar: { display: 'flex', alignItems: 'center', gap: '1rem', backgroundColor: '#ffffff', padding: '1rem 1.5rem', borderRadius: '10px', border: '1px solid #e5e7eb', flexWrap: 'wrap' },
  codeLabel: { fontSize: '0.9rem', fontWeight: '700', color: '#374151' },
  codeSelectDropdown: { padding: '0.45rem 0.85rem', borderRadius: '6px', border: '2px solid #0284c7', fontSize: '0.92rem', fontWeight: '700', color: '#0369a1', backgroundColor: '#f0f9ff', outline: 'none' },
  codeInput: { padding: '0.45rem 0.85rem', borderRadius: '6px', border: '2px solid #2563eb', fontSize: '1rem', fontWeight: '800', color: '#1d4ed8', fontFamily: 'monospace', textTransform: 'uppercase' },
  refreshSessionsBtn: { padding: '0.45rem 0.85rem', borderRadius: '6px', border: '1px solid #cbd5e1', backgroundColor: '#f8fafc', color: '#334155', fontWeight: '700', fontSize: '0.85rem', cursor: 'pointer' },
};
